export enum DispatchActionEnum {
  SET_AS_NEW = 1,
  SET_AS_INPROGRESS = 2,
  SET_AS_READY = 3,
  SET_AS_SCHEDUALED = 4,
  ADDED_TO_TRIP = 5,
  CHANGE_TRIP = 6,
  PAUSE_ORDER = 7,
  UNPAUSE_ORDER = 8,
  REMOVE_FROM_TRIP = 9,
}