export enum TripActionEnum {
    NON = 0,
    CREATED = 1,
    READY = 2,
    SEND_REQUEST_TO_DELIVERYMAN = 3,
    REQUEST_ACCEPTED = 4,
    REQUEST_DECLINED = 5,
    REQUEST_IGNORED = 6,
    REQUEST_EXPIRED = 7,
    REQUEST_IGNORED_AFTER_ACCEPTED = 8,
    HOLDED = 8,
    STARTED = 9,
    CANCELED = 10,
    DELIVERED = 11,
    COMPLETED = 12,
    DELIVER_ORDER = 13,
    REMOVE_ORDER = 14,
    CHANGE_DELIVERYMAN = 15,
    ASSIGN_DELIVERYMAN = 16,
    READY_AFTER_IGNORED = 17,
    READY_AFTER_EXPIRED = 18,
    DELETED = 19,
    ORDER_CANCELED = 20,
    RECIEVED = 21,
    ADD_ORDER_TO_TRIP = 22,
    AUTO_CANCEL_SPECIAL_TRIP = 23,
    CAN_NOT_DELIVER_ORDER = 24,
    FAILEDTOSTART = 25,
    ARRIVE_AT_BRANCH = 26,
    RECEIVED_ORDER = 27,
    
    
    

}

